# Generated by Django 5.1.2 on 2024-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variacao_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
